const moment = require('moment')
const a = moment().format('YYYY-MM-DD')
const b = moment().format('dddd')
const c=moment().format('MMM Do YY')
const d = moment().format()
const e = moment('20010125','YYYYMMDD').fromNow()
const f = moment().startOf("day").fromNow()
const g = moment().endOf('day').fromNow()
const h = moment().startOf("hour").fromNow()
const i = moment().subtract(10,'days').calendar()
const j = moment().calendar()
const k = moment().add(1, 'days').calendar()
const l = moment.locale()
const m = moment().format('LT')
const n = moment().format('LTS')
const o = moment().format('L')
const p = moment().format('l')
const q = moment().format('LL')
const r = moment().format('ll')
const s = moment().format('LLL')
const t = moment().format('lll')
const u = moment().format('LLLL')
const v = moment().format('llll')
console.log(a)
console.log(b)
console.log(c)
console.log(d)
console.log(e)
console.log(f)
console.log(g)
console.log(h)
console.log(i)
console.log(j)
console.log(k)
console.log(l)
console.log(m)
console.log(n)
console.log(o)
console.log(p)
console.log(q)
console.log(r)
console.log(s)
console.log(t)
console.log(u)
console.log(v)
